import React from 'react';
import '../styles/AIContentBadge.css';

export type ContentSource = 'ai' | 'human' | 'ai-assisted';

interface AIContentBadgeProps {
  source: ContentSource;
  modelName?: string;
  size?: 'small' | 'medium' | 'large';
  showIcon?: boolean;
}

const AIContentBadge: React.FC<AIContentBadgeProps> = ({
  source,
  modelName,
  size = 'medium',
  showIcon = true,
}) => {
  const getBadgeConfig = () => {
    switch (source) {
      case 'ai':
        return {
          label: 'AI Generated',
          className: 'ai-badge-ai',
          icon: '🤖',
          description: 'This content was generated by AI',
        };
      case 'ai-assisted':
        return {
          label: 'AI Assisted',
          className: 'ai-badge-assisted',
          icon: '✨',
          description: 'This content was created with AI assistance and edited by a human',
        };
      case 'human':
        return {
          label: 'Human Created',
          className: 'ai-badge-human',
          icon: '👤',
          description: 'This content was created entirely by a human',
        };
    }
  };

  const config = getBadgeConfig();

  return (
    <div
      className={`ai-content-badge ai-badge-${size} ${config.className}`}
      title={config.description}
      role="status"
      aria-label={config.description}
    >
      {showIcon && <span className="ai-badge-icon">{config.icon}</span>}
      <span className="ai-badge-label">{config.label}</span>
      {modelName && <span className="ai-badge-model">({modelName})</span>}
    </div>
  );
};

export default AIContentBadge;
